### ISSUE TITLE
Hide all internal services behind one url

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6279]

**Comment by rikukissa** [comment]
Related https://github.com/opencrvs/opencrvs-core/issues/6869

**Comment by rikukissa** [comment]
Related https://github.com/opencrvs/opencrvs-core/issues/6692

**Comment by rikukissa** [comment]
This task need to be prioritised as we frequently have mission-critical data exposed from different services. For example, the certificates are available without authorisation.

https://countryconfig.farajaland-qa.opencrvs.org/certificates

**Comment by SyedaAfrida** [comment]
@rikukissa Can this be closed? If not please mention the correct Issue type.

**Comment by adskyiproger** [comment]
What if we use traefik or Kubernetes Gateway API to solve this issue?

E/g:

Current:
```yaml
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-route
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`{{ include "render-external-subdomain" (dict "service_name" "minio" "Values" .Values) }}`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3535
  - match: 'Host(`{{ include "render-external-subdomain" (dict "service_name" "minio-console" "Values" .Values) }}`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3536
```

Single sub-domain:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-route
spec:
  entryPoints:
  {{- if .Values.ingress.ssl_enabled }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`{{ .Values.hostname }}`) && PathPrefix(`/minio`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3535

  - match: 'Host(`{{ .Values.hostname }}`) && PathPrefix(`/minio-console`)'
    kind: Rule
    services:
    - name: minio
      namespace: {{ .Release.Namespace }}
      port: 3536
```

If you are fine with this solution, I can work on it in near future

cc @rikukissa
