### ISSUE TITLE
Forward Kibana alerts to from Elastalert to country config service

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#6437]
### Description

This deprecates email API key and let's countries configure email only once – in their country config code. 
This is also needed because Elastalert doesn't work with Office365. 

Configure Elastalert to send HTTP requests to country config instead of sending messages directly. This way we can use SMTP details and we can deprecate EMAIL_API_KEY & ELASTALERT_SLACK_WEBHOOK entirely.

### How to test
- [ ] If any emails work (2FA, informant messaging) then this did not cause regression
- [x] Trigger an alert, verify email received from Elastalert

### Dev tasks

- [x] Create a new endpoint POST `/email` in country config. This endpoint sends an email based on given input

Request payload
```
{
  body: string,
  from: string,
  subject: string,
  to: string
}
```
- [x] Configure Elastalert to use this endpoint to submit errors to. [Reference](https://elastalert.readthedocs.io/en/latest/ruletypes.html#http-post)
- [x] Configure Traefik to block requests to the /email endpoint. Only Elastalert should be able to call it through the internal network.

```yml
  countryconfig:
    deploy:
      labels:
        # ... [existing labels] ...
        - 'traefik.http.middlewares.block-all.ipwhitelist.sourcerange=255.255.255.255'  # This is an invalid IP range, effectively blocking all IPs
        - 'traefik.http.routers.email-blocker.rule=Path(`/email`)'
        - 'traefik.http.routers.email-blocker.middlewares=block-all'
```

- [x] Deploy to dev – verify it works
- [x] Verify endpoint in a deployed environment cannot be accessed from the public internet
- [x] Remove all references to Email API key and `ELASTALERT_SLACK_WEBHOOK`
