### ISSUE TITLE
Storybook is not being built into opencrvs/components docker image

### ISSUE THREAD

**Issue by rikukissa** [opencrvs/opencrvs-core#7440]
![Image](https://github.com/user-attachments/assets/df0b94c7-a640-475f-bdbc-1922d3f84101)

### Description

Storybook is not currently available in deployed OpenCRVS environments. This seems to be because of an error when components package is being built

```
#19 2.656 info => Building manager..
#19 2.754 ✘ [ERROR] Could not resolve "@opencrvs/components/lib/theme"
#19 2.754 
#19 2.754     .storybook/theme.ts:12:25:
#19 2.754       12 │ import { getTheme } from '@opencrvs/components/lib/theme'
#19 2.754          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#19 2.754 
#19 2.754   You can mark the path "@opencrvs/components/lib/theme" as external to exclude it from the bundle, which will remove this error.
#19 2.754 
#19 2.822 Error: Build failed with 1 error:
#19 2.822 .storybook/theme.ts:12:25: ERROR: Could not resolve "@opencrvs/components/lib/theme"
#19 2.822     at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1649:15)
#19 2.822     at /app/node_modules/esbuild/lib/main.js:1058:25
#19 2.822     at runOnEndCallbacks (/app/node_modules/esbuild/lib/main.js:1484:45)
#19 2.822     at buildResponseToResult (/app/node_modules/esbuild/lib/main.js:1056:7)
#19 2.822     at /app/node_modules/esbuild/lib/main.js:1085:16
#19 2.822     at responseCallbacks.<computed> (/app/node_modules/esbuild/lib/main.js:703:9)
#19 2.822     at handleIncomingPacket (/app/node_modules/esbuild/lib/main.js:762:9)
#19 2.822     at Socket.readFromStdout (/app/node_modules/esbuild/lib/main.js:679:7)
#19 2.822     at Socket.emit (node:events:517:28)
#19 2.822     at addChunk (node:internal/streams/readable:368:12)
#19 2.834 info Found existing addon "@storybook/addon-docs", skipping.
```

### Tasks

- [ ] Research what causes the error. Ensure docker image build fails if there is a similar error in the future. Fix the root cause for the issue
- [ ] Verify https://ui-kit.farajaland-dev.opencrvs.org/ is available after your PR is merged and automated E2E deployment done

**Comment by naftis** [comment]
@rikukissa How is the error reproduced? Should a specific Github Action be ran? I'm failing to build the Docker images on my local machine for other reasons*, meanwhile `yarn build` runs fine.

* `ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 95c952a2-459e-4992-a0fa-41b5ad731abe::zcm6zzsw215elk3uet6lqpg5o: failed to walk /var/lib/docker/tmp/buildkit-mount1982967502/infrastructure: lstat /var/lib/docker/tmp/buildkit-mount1982967502/infrastructure: no such file or directory`
(not sure if they even should be buildable locally)

**Comment by naftis** [comment]
The issue here is that the Dockerfile doesn't first run `yarn build` to build the components. I'd say it makes most sense to deploy it outside of the actual installations though, similar to documentation. We could use Cloudflare Pages, Netlify or Github Pages. 

We can deploy the Storybook with an action like this:
```
name: Build and Deploy Storybook to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "opencrvs/opencrvs-core"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      - name: Install dependencies
        run: yarn install
      # @TODO: when Yarn 2 is available
      #  run: yarn workspaces focus --production @opencrvs/components

      - name: Build components
        run: cd packages/components && yarn build

      - name: Build Storybook
        run: cd packages/components && yarn build-storybook

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-cli@0e5db3233380b841d6e0dfd3b1eef306c6c79735 #v2.0.0
        id: netlify
        with:
          args: 'deploy --json --prod --dir \"./packages/components/build\" --message \"draft [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```
