### ISSUE TITLE
Spacing variables missing from the design system

### ISSUE THREAD

**Issue by Eezi** [opencrvs/opencrvs-core#9017]
## Describe the improvement
Hey!

I noticed that the design system of the Opencrvs is currently lacks spacing variables, or I couldn’t find them in the file: "packages/components/src/theme.ts". What do you think—should we add spacing variables to the theme?

I generated some example responsive variables using Utopia (https://utopia.fyi/).
Here are the examples:

```ts
export const spacing = {
  '3xs': 'clamp(0.3125rem, 0.3125rem + 0vw, 0.3125rem)',
  '2xs': 'clamp(0.5625rem, 0.5408rem + 0.1087vw, 0.625rem)',
  xs: 'clamp(0.875rem, 0.8533rem + 0.1087vw, 0.9375rem)',
  s: 'clamp(1.125rem, 1.0815rem + 0.2174vw, 1.25rem)',
  m: 'clamp(1.6875rem, 1.6223rem + 0.3261vw, 1.875rem)',
  l: 'clamp(2.25rem, 2.163rem + 0.4348vw, 2.5rem)',
  xl: 'clamp(3.375rem, 3.2446rem + 0.6522vw, 3.75rem)',
  '2xl': 'clamp(4.5rem, 4.3261rem + 0.8696vw, 5rem)',
  '3xl': 'clamp(6.75rem, 6.4891rem + 1.3043vw, 7.5rem)'
}

```

## Pitch
With these spacing variables we could improve spacing consistency of the design system.
We could add the variables to the theme and implement them little by little. That way, adding them shouldn't cause a lot of extra work.

**Comment by naftis** [comment]
Thank you for the initiative, @Eezi! 

I fully support this from a technical perspective. Before proceeding, I'd like to check with @jpye-finch and @Alta-Nel: 

- In the **Figma design system**, do we already have spacing variables defined?
- If so, how closely do they align with this proposed scale?
- If not, should we define them now and ensure consistency between design and code?

After getting feedback from design, I suggest:
1. Creating a pull request to amend the theme as proposed.
2. Refactoring a single component (perhaps `Frame`?) as an example of implementation.

---

**Draft Spacing Table**  
(Assuming a root font size of `16px`; we should confirm whether we define this explicitly, and if not, consider setting it to `font-size: 100%; /* Keeps the default browser setting */`)

| Size  | Pixels | rem (based on 16px) | Suggested Use Cases                     |
|-------|--------|---------------------|-----------------------------------------|
| 3xs   | 2px    | 0.125rem            | Hairline borders, ultra-fine details   |
| 2xs   | 4px    | 0.25rem             | Thin dividers, small spacing           |
| xs    | 8px    | 0.5rem              | Small padding, tight spacing           |
| s     | 12px   | 0.75rem             | Labels, captions, compact UI elements  |
| m     | 16px   | 1rem                | Default body text, standard spacing    |
| l     | 24px   | 1.5rem              | Subheadings, moderate padding/margins  |
| xl    | 32px   | 2rem                | Headings, large buttons                |
| 2xl   | 48px   | 3rem                | Section headers, major UI elements     |
| 3xl   | 72px   | 4.5rem              | Hero sections, very large text         |

**Comment by Eezi** [comment]
I also noticed that the typography of the theme is using the pixels as a font size. Should we also change them to be more responsive? Of course, this could be done separately later.

**Comment by jpye-finch** [comment]
@Eezi many thanks for your initiative on this!

We have wanted to make fonts and spacing responsive to desktop/mobile for some time. 

@Alta-Nel can help support on defining the values and approach.

FYI. We have also discussed briefly moving away from using a custom front-end with styled-components to using an existing design system such as Tailwind CSS and Radix Ui. That we customise from there.  ...but we are some way off from doing so.

**Comment by naftis** [comment]
> What do you think [@naftis](https://github.com/naftis)? Should we use the clamp function during implementation or just use the rem unit? The clamp function would allow the spacing values ​​to adapt to the screen size, which would reduce the need for breakpoints.

Yep, I like it and support that as well.

Our design system will likely have 3 different designs: mobile, tablet, and desktop. @Alta-Nel is this the case or does the new design system introduce a different responsiveness?

Within these breakpoints, for design team to be able to validate the eventual deployed UI, I think we need to define something like:
* mobile (screen width is 640px): `m` is 14px
* tablet (screen width is 1280px): `m` is 16px
* desktop (screen width is 1920px): `m` is 18px

I'm open to suggestions how this could be implemented, or should we look the spacing from a not-so-pixel-strict perspective? @Eezi

**Comment by Eezi** [comment]
I agree that we should not aim for pixel perfection. How about if I first open a new PR where I would add spacing variables to the project theme. Then we would modify a few simple components' pixel spacing values with these new variables and test how they look on different screen sizes.  

Now the variables are generated based on the min screen (320px) font size (14px) and max screen (1920px) font size (18px). We can later adjust the spacing values based on the Figma design.

Variables would look like as below:

```css
/* @link https://utopia.fyi/space/calculator?c=320,14,1.2,1920,18,1.25,5,2,&s=0.75|0.2|0.1,1.5|2|3|4|6,s-l&g=s,l,xl,12 */

:root {
  --space-3xs: clamp(0.0625rem, 0.05rem + 0.0625vw, 0.125rem);
  --space-2xs: clamp(0.1875rem, 0.175rem + 0.0625vw, 0.25rem);
  --space-xs: clamp(0.6875rem, 0.65rem + 0.1875vw, 0.875rem);
  --space-s: clamp(0.875rem, 0.825rem + 0.25vw, 1.125rem);
  --space-m: clamp(1.3125rem, 1.2375rem + 0.375vw, 1.6875rem);
  --space-l: clamp(1.75rem, 1.65rem + 0.5vw, 2.25rem);
  --space-xl: clamp(2.625rem, 2.475rem + 0.75vw, 3.375rem);
  --space-2xl: clamp(3.5rem, 3.3rem + 1vw, 4.5rem);
  --space-3xl: clamp(5.25rem, 4.95rem + 1.5vw, 6.75rem);

}
```
