### ISSUE TITLE
Setup kubernetes cluster on Hetzner for e2e environment

### ISSUE THREAD

**Issue by adskyiproger** [opencrvs/opencrvs-core#9728]
### Description

Setup kubernetes cluster on Hetzner

### Acceptance criteria

- terraform script to provision multiple VMs on Hetzner
- Ansible script to setup cluster
   - Install traefik
   - Install Cert manager
   - Install self-hosted runner

**Comment by alsmk** [comment]
We will accomplish these tasks using Ansible. The setup will involve a single playbook that references multiple task files, ensuring modularity and maintainability. The proposed file structure is as follows:
```
k8s-cluster/
├── inventory.ini
├── setup-k8s-cluster.yml
├── tasks/
│   ├── disable-swap.yml
│   ├── containerd.yml
│   ├── install-kubernetes.yml
│   ├── master-init.yml
│   ├── worker-join.yml
│   └── install-cni.yml
```
This structure will help us keep the roles and responsibilities of each step clear and organized throughout the Kubernetes cluster provisioning process.

Let's begin with the inventory file. This file defines the hosts in our Kubernetes cluster and groups them into roles. A sample structure might look like the following:
```
[master]
e2e-k8s-master=157.180.19.137
[workers]
e2e-k8s-worker-0=95.217.10.199
e2e-k8s-worker-1=157.180.92.109
[kubernetes:children]
master
workers

[kubernetes:vars]
ansible_user=provision
ansible_ssh_private_key_file=~/.ssh/your_private_key

```
Let's go through the tasks one by one, starting with disabling swap. The file `tasks/disable-swap.yml` would look like:
```
- name: Disable swap
  command: swapoff -a

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^\s*([^#].*\sswap\s)'
    replace: '# \1'

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Persist kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Apply sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Reload sysctl
  command: sysctl --system

```
Install and restart the containerd service. The tasks/containerd.yml task file should look like this:

```
- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: true

- name: Generate default config
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    name: containerd
    enabled: true
    state: restarted

```
And the taks for installing kubernetes `tasks/install-kubernetes.yml` is :

```
- name: Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Hold Kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl
```
After installing we have to Initialize the master node: 
```
- name: Initialize Kubernetes master
  shell: kubeadm init --pod-network-cidr=10.0.0.1/16 [chnages to be made]
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory for provision user
  file:
    path: /home/provision/.kube
    state: directory
    owner: provision
    group: provision
    mode: 0755

- name: Copy admin.conf to provision's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/provision/.kube/config
    remote_src: yes
    owner: provision
    group: provision
    mode: 0644

- name: Save join command
  shell: kubeadm token create --print-join-command > /joincluster.sh

```
Allow the worker nodes to join the cluster using the following task:

```
- name: Get join command from master
  shell: cat /joincluster.sh
  register: join_command
  delegate_to: master

- name: Join node to the cluster
  shell: "{{ join_command.stdout }}"
```
And the final task is to install CNI:
```
- name: Install Flannel CNI
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /home/provision/.kube/config
```
The playbook that executes all the tasks on the respective hosts will look like this:
```
- name: Kubernetes Prerequisites
  hosts: kubernetes
  become: true
  tasks:
    - include_tasks: tasks/disable-swap.yml
    - include_tasks: tasks/containerd.yml
    - include_tasks: tasks/install-kubernetes.yml

- name: Initialize Master Node
  hosts: master
  become: true
  tasks:
    - include_tasks: tasks/master-init.yml

- name: Join Worker Nodes
  hosts: workers
  become: true
  tasks:
    - include_tasks: tasks/worker-join.yml

- name: Install CNI Plugin (Flannel)
  hosts: master
  become: true
  tasks:
    - include_tasks: tasks/install-cni.yml
```
