### ISSUE TITLE
Make it configurable for countries to add a whitelist device ID header

### ISSUE THREAD

**Issue by euanmillar** [opencrvs/opencrvs-core#9782]
## 🚀 Feature
Some countries do not want to provision a VPN.  There is a suggestion to allow the configuration of a signed device ID on every request, with a middleware that forwards requests that do not have a trusted device ID to an unauthorised URL

## Pitch
This secures OpenCRVS without the need for a VPN

## Triggers
This would make provisioning of OpenCRVS easier for low resource settings

## Standard flow
An admin uses a companion app to register trusted device IDs for users

## Technical approach
:white_check_mark: Custom headers + Traefik Middleware + ForwardAuth
Here’s a secure and scalable approach:
:wrench: 1. Pass the Device ID via HTTP Header
From the client (e.g., mobile app or browser), attach a custom header to each request:
E.G.
```
X-Device-ID: abc123
```
:toolbox: 2. Create a ForwardAuth Middleware
Traefik will call an external service to check each request.
:white_check_mark: YCheck if X-Device-ID is in your whitelist (stored in a DB populated by a companion app)
If allowed, return 200 OK
If missing or disallowed, return a 302 Redirect to another site
:frame_with_picture: Sample Node.js Express auth server:
```
app.get('/auth', (req, res) => {
  const deviceId = req.get('x-device-id');
  const whitelist = ['abc123', 'xyz789']; // You can load this dynamically

  if (!deviceId || !whitelist.includes(deviceId)) {
    return res.redirect(302, '
https://example.com/unauthorized');
  }

  return res.sendStatus(200);
});
```
:gear: 3. Configure Traefik with ForwardAuth
```
http:
  middlewares:
    device-auth:
      forwardAuth:
        address: "
http://auth-service.local/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Device-ID"

  routers:
    my-router:
      rule: "Host(`yourdomain.com`)"
      entryPoints:
        - websecure
      service: your-service
      middlewares:
        - device-auth
     ``` 
This setup will:
Accept only requests with a valid X-Device-ID
Redirect others to https://example.com/unauthorized
